from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol


class WorkbookEngine(Protocol):
    def sheet_names(self) -> list[str]: ...
    def read_cell(self, sheet: str, row: int, column: int) -> Any: ...
    def write_cell(self, sheet: str, row: int, column: int, value: Any) -> None: ...
    def create_sheet(self, name: str) -> None: ...
    def save(self, path: Path) -> None: ...
    def close(self) -> None: ...
